const samKar = [
['sk 0 싸앙크야 까리까', 
'상크야 철학의 압축된 운문',
'(보충설명-해제) ', 
'sāṃkhya kārika',
'sāṃkhya: 수에 관한, 수를 잘 세는 사람, 힌두 3대 철학의 하나',
'kārikā: 압축적인 운문',
    ],
['sk 1 세가지 고통:',
'세 가지 고통의* 공격으로부터, 그것(고통)을 제거하는 원인을 알고싶지만/ 본(경험한) 것에서는 의미 없었다. 혹 (의미가) 있었다고 해도, (고통은) 확실히 절대적으로 없어지지도 않았다.',

'(보충설명) *세가지 고통은 내적인 것, 외적인 것, 신적인 것이다. 내적인 고통은 정신적인 것, 육체적인 것이 있고, 외적인 고통은 인간이나 동물이나 자연에 의한 것이 있고, 신적인 고통은 초자연적 존재들에 의한 것이다. ',

'duḥkha-trayā-abhighātāt-jijñāsā tat-abhighātake hetau | dṛṣṭe sā-apārthā cet na-ekānta-atyantataḥ abhāvāt ||',

'duḥkha: 고통',
'trayā: 셋',
'abhighāta: (~āt, 원형 han, 남성단수종격) 공격, 때림',
'jijñāsā: (jijñāsana의 여성형) 알고싶음',
'tat: 그것',
'abhighātaka: (~e, 처격, ~ka는 형용사를 만드는 접미사) (공격을) 제거하는, 반응하는',
'hetu: (~au, 처격) 원인',
'dṛṣṭa: (~e, 처격) 본 것 ',
'sā: 그것(그녀)은 ( 알고싶음을 가르킴) ',
'apārthā: 의미없음, 쓸데없음 ',
'cet: ced, 그렇다고 해도, 혹은',
'na:아니다',
'ekānta: 절대적으로, 확실히',
'atyanta :(~tas, 는 부사를 만드는 접미사) 완전히, 절대적으로',
'abhāva: (~āt, 종격) 없어짐',
],
[
'sk 2 고통의 해결자:',
'본(경험한) 것처럼, 들은 것(베다경전)도, 불순하고, 파괴적이고 지나치게 제어된 것이다. / 그것과 다른 더 나은 것이 (필요하다). 드러난것, 드러나지않은것, 아는자 (셋)를 식별함으로써.',

'(보충설명) 싸앙크야 경은 25가지 원리(땃뜨바)로 세상을 설명한다. 드러난 것은, 붓디(지성, 마하트), 아함까라(자의식), 5가지 미세요소(오유, 색성향미촉), 마음(마나스), 다섯 감각기관(안이비설신), 다섯 행위기관(손,발,입,항문,성기), 다섯 거친요소(오대, 지수화풍공)로 모두 23가지이다. 드러나지 않은 것은 원질(쁘라끄리띠)이다. 아는자는 뿌루샤(정신)이다.',
'dṛṣṭavat-ānu-śravikaḥ saḥ hi-aviśuddhi-kṣayā-atiśaya-yuktaḥ | tat-viparītaḥ śreyān vyaktāvyakta-jña-vijñānāt ||',

'dṛṣṭa: 본 것',
'vat: 처럼',
'ānuśravika:(~ḥ,남성단수주격) (반복해서) 들은 것(베다 경전)',
'sa:(~ḥ,남성단수주격) 그것',
'hi: ~도',
'aviśuddhi: 깨끗하지 않음, 성스럽지 않음, 불순함',
'kṣaya: 파괴적, 낭비적',
'atiśaya: 탁월한, 지나친, 매우',
'yukta: (~ḥ,남성단수주격)제어된, 연결된, 시설된',
'tat: 그',
'viparīta: 반대의, 뒤집어진, 다른',
'śreyas: (~ān, śreyaṃs의 단수주격) 더 좋은, 더 훌륭한',
'vyakta: 드러난 것',
'avyakta: 드러나지 않은 것(*원질(쁘라끄리띠)를 말한다',
'jña: 아는자, 보는자(*순수정신(뿌루샤)를 말한다)',
'vijñāna:(~āt, 종격) 식별, 구별',
],
[
'sk 3 원질:',
'근본 원질(쁘라끄리띠)은 변화인(변하는 것)이 아닌 위대한 시원의 근원이다. 원질에서 (나온) 변화인들은 7가지이다. 그러나 변화과(변화되는 것)들은 16가지이다. 정신(뿌루샤)은 원질도 아니고 변화인도 아니다.',

'(보충설명) 원질(쁘라끄리띠)에서 나온 변화인(변화를 일으키는 것)은 7가지이다. 붓디(지성, 마하트), 아함까라(자의식), 그리고 5가지 미세요소(오유, 색성향미촉)이다. 이들 변화인으로부터 변화과(변화되는 것) 16가지가 만들어진다. <br> 11가지 감관(indriya)과 다섯 가지 거친요소(오대, 지수화풍공)이다. 11가지 감관은 마음(manas)를 비롯해 다섯 감각기관(안이비설신)과 다섯 행위기관(손,발, 입, 생식기, 배설기)이다. ',

'mūla-prakṛtiḥ avikṛtiḥ maha-ādādyāḥ prakṛti-vikṛtayaḥ sapta |ṣoḍaśakaḥ tu vikāraḥ na prakṛtiḥ na vikṛtiḥ puruṣaḥ ||',

'mūla prakṛti: 근본 원질',
'avikṛti: (~ḥ, 여성단수주격) 변화인이 아닌, 변화를 일으키는 것이 아닌',
'maha: 위대한',
'ādā: 시원, 착수',
'ādya: (~āh, 여성복수주격) 근원, 머리, 시초',
'prakṛti: 원질, 변화인',
'vikṛti: (~ayah, 여성복수주격) 변화인, 변화를 일으키는 것',
'sapta: 7 ',
'ṣoḍaśaka:16 ',
'tu: 그러나',
'vikāra: 변화과, 변화되는 것',
'na prakṛti:원질이 아니다',
'na vikṛti: 변화인이 아니다',
'puruṣa: 정신, 순수정신',
],
[
'sk 4 세가지 바른 인식:',
'지각, 추론, 성언이 모두 바른인식의 성취성이기에/ 옳다고 여겨지는 바른인식은 세 종류이다. 증명(확인)되어야할 성취는 바른인식으로 (얻기) 때문이다.',

'(보충설명) ',
'dṛṣṭam-anumānam-āpta-vacanaṃ ca sarva-pramāṇa-siddhatvāt | tri-vidhaṃ pramāṇam-iṣṭaṃ prameya-siddhiḥ pramāṇāt-hi ||',

'dṛṣṭa: 본 것, 지각',
'anumāna: 추론',
'āpta-vacanaṃ: 성언, 성자의 말',
'ca:그리고',
'sarva: 모든',
'pramāṇa: 바른 지각, 바른 인식',
'siddhatva: 성취, 증거',
'trividha:세 종류',
'pramāṇa: 바른지각',
'iṣṭa: 원하는, 바라는, 옳다고 여겨지는',
'prameya: 증명되어야 할, 확인되어야 할',
'siddhi: 획득, 성취, 이행',
'prameya siddhi:확인(증명)되어야할 성취(*싸앙크야 철학의 25가지 원리, Sinha 1915)',
'pramāṇa: 바른 지각, 바른 인식',
'hi: ~도',
],
[
'sk 5 지각 추론 성언:',
'지각은 대상의 감각적 확인이다. 추론은 링가(표식하는것, 술어)와 링기(표식된것, 주어)로 된 것으로 3 종류*로 말해진다. 앞서서 획득한 자에게 들은 것이 성언(스루띠)이다.',

'(보충설명) 추론의 3 가지는 선행, 후행, 일반 추론 이다. 선행추론은 구름이 모인 것을 보고 비가 올 것을 추론하는 것이고, 후행추론은 바닷물방울이 짠 것을 보고 바닷물이 짜다고 추론하는 것이고, 일반 추론은 한 사람이 자리를 옮기는 것을 보고 달이나 별이 자리를 옮기는 것으로 추론하는 것이고, 마찬가지로 한 곳의 망고나무가 꽃이 피는 것을 보고 모든 망고나무는 꽃이 핀다고 추론하는 것이라는 설명이다. ',
'prati-viṣaya-adhyavasāyaḥ dṛṣṭaṃ tri-vidham-anumānam-ākhyātam |tat-liṅga-liṅgi-pūrvakam-āpta-śrutiḥ āpta-vacanaṃ tu ||',

'prati: ~향하여',
'viṣaya: 대상',
'adhyavasāya:(~ḥ, 남성단수주격) 감각으로 확인(판단, 결정), 정신적 노력',
'dṛṣṭa: (중성단수주격) 본 것 , 지각',
'tri-vidham:세 종류',
'anumāna: 추론',
'ākhyāta: 말해진, 알려진',
'tat: 그것',
'liṅga: 표식하는 것, 술어, 형식?',
'liṅgi: 표식된 것, 주어, 내용?',
'pūrvaka: 앞선, 선행의',
'āpta: 얻은 (자), 획득한 (자)',
'śruti: 들은 것, 경전',
'āpta vacana: 성언 ',
'tu:그러나',
],
[
'sk 6 지각 추론 성언:',
'그러나 인식이 본(지각한) 것으로부터 (얻어지는 것과 ) 유사하게, 추론으로부터 감각을 초월한 것들의 (바른인식을 한다). 또 그것으로도 확인되지 않는 것은, 초감각을 획득한 성취한 자의 말(경전)로 (바른인식을) 한다.',

'(보충설명) ',
'sāmānyataḥ tu dṛṣṭāt-atīndriyāṇāṃ pratītiḥ anumānāt |tasmāt-api ca-asiddhaṃ parokṣam-āpta-āgamāt-siddham ||',

'sāmānyatas:(불변화사) 유사하게, 일반적으로',
'tu: 그러나',
'dṛṣṭa:(āt, 중성단수종격) 본 것, 지각',
'atīndriya :(~āṇā, 중성복수속격) 감각을 넘는',
'pratīti: (~ḥ, 여성단수주격) 직관, 인식, 분명한 이해',
'anumāna: 추론',
'tasmāt 그것으로',
'api:~도',
'ca:또한',
'asiddha:(~ṃ, 중성단수주격) 증명(확인, 성취)되지 않은',
'parokṣa: 초감각',
'āpta: 성자',
'āgama: 경전',
'siddha:(~m, 중성단수대격) 증명된, 확인된, 성취된',
],
[
'sk 7 지각되지 않는 것:',
'아주 멀거나 가깝거나 감관이 손상되었거나, 마음이 머물지 않거나/ 미세하거나, (다른 것들의) 방해를 받거나, 압도되어 있거나, 비슷한 것들이 섞여 있어도 (지각되지 않는다)',

'(보충설명) ',
'atidūrāt sāmīpyāt-indriya-ghātāt-manas-anavasthānāt |saukṣmyāt-vyavadhānāt-abhibhavāt samāna-abhihārāt-ca ||',

'atidūra:(~āt, 중성단수종격) 아주 먼',
'sāmīpya:(~āt, 중성단수종격) 가까운',
'indriya: 감각, 감관',
'ghāta:(~āt, 중성단수종격) 다친, 손상된, 상처입은',
'manas: 마음',
'anavasthāna:(~āt, 중성단수종격) 머물지 않은, 들어가지 않은',
'saukṣmya :sūkṣma:(~āt, 중성단수종격) 미세한',
'vyavadhāna:(~āt, 중성단수종격) 방해',
'abhibhava:(~āt, 중성단수종격) 눌림, 압도',
'samāna: 비슷한',
'abhihāra:(~āt, 중성단수종격) 섞인',
'ca:또한',
],
[
'sk 8 드러나지 않은 것(쁘라끄리띠):',
'그것(쁘라끄리띠)이 지각되지 않는 것은, 변화로 획득된 것이 없어서가 아니라 미세하기 때문이다.  마하트(변화인)를 비롯해서 또 그 변화된 것(변화과)은, 쁘라끄리띠와 닮았거나 닮지 않았다. ',

'(보충설명) ',
'saukṣmyāt-tat-anupalabdhiḥ nābhāvāt kāryataḥ tat-upalabdheḥ |mahat-ādi tat-ca kāryaṃ prakṛtisarūpaṃ virūpaṃ ca ||',

'sūkṣma: (~āt, 중성단수종격) 미세한',
'tat: 그것',
'anupalabdhi:(an+ upalabdhi) 지각되지 않음',
'na: 아니다',
'abhāva: 있지 않다',
'kāryata: (~ḥ, 중성단수속격) 만들어진 상태, 일어난 상태, 변화된 결과',
'upalabdhi:(~eh, 여성단수속격) 획득, 지각',
'mahat: 위대한 것, 마하트',
'ādi: 시작',
'ca: 또한',
'kārya: 만들어진, 일어난, 결과',
'prakṛti: 원질',
'sarūpa: 같은 형태, 닮은 모습',
'virūpa:  다양한, 다른 모습',
'ca: 또한',
],
[
'sk 9 원인 결과:',
'(일어난) 결과는 (원인에 이미) 존재한다. 1) 비존재는 원인이 없기 때문이고, 2)획득된(지각한) 것은 붙잡아야(선택해야) 하기 때문이고, 3)모든 것이 함께 결합되지 않기 때문이고, 4)가능한 것은 가능한(그럴만한) 작용이 있어야 하기 때문이고, 5)원인이 있어야 하기 때문이다.',

'(보충설명) ',
'asat-akaraṇāt-upādāna-grahaṇāt sarva-saṃbhavā-abhāvāt | śaktasya śakyakaraṇāt kāraṇa-bhāvāt-ca sat-kāryam ||',

'asat:비존재, 존재하지 않음',
'akaraṇa:(~āt, 중성단수종격) 일어나지 않는, 작용하지 않는, 원인 없는',
'upādāna: 획득된, 지각된',
'grahaṇa: (~āt, 중성단수종격) 포착하는,  붙잡는',
'sarva: 모든',
'saṃbhava:(~ā, 여성형?) 결합',
'abhāva:(~āt, 중성단수종격) 되지 않음, 있지 않음',
'śakta: (~sya, 중성단수속격) 가능한',
'śakya: 가능해진, 그럴만한',
'karaṇa:(~āt, 중성단수종격) 일어나는, 작용하는, 원인, 기관',
'kāraṇa: 원인',
'bhāva:(~āt, 중성단수종격) 됨, 있음',
'ca: 또한',
'sat: 존재',
'kārya: (~m, 중성단수주격) 만들어진, 일어난, 결과',
],
[
'sk10 드러난것:',
' 드러난 것*은, 영원하지 않고(무상), (모든 곳에) 충만하지 않으며, 활동하고(변하고), 다수이고, 의존하고, 링가(표식)가 되는 것이다. (추론의) 표식이 되는 것(링가)이고, 부분이고(결합하고), 보조적이다. 드러나지 않은 것*은 그 반대다.',

'(보충설명) *싸앙크야 철학의 25가지 원리 가운데서 드러난 것은, 원질(쁘라끄리띠)과 순수정신(뿌루샤)을 제외한 23가지를 말한다. 즉 붓디(지성),아함까라(자의식), 5가지 미세요소(오유, 색성향미촉), 5가지 감각기관(눈 귀 코 혀 피부)과 5가지 행위기관(손 발 입 항문 성기) 그리고 마음이다. 경문2 참조. <br> 드러나지 않은 것은 원질(쁘라끄리띠)을 말한다. 경문2 참조. <br> *링가는 바네르지의 주석에 의하면 주석자들의 의견이 두 가지로 갈린다.  ',
'hetumat-anityam-avyāpi sakriyam-anekam-āśritaṃ liṅgam |sāvayavaṃ paratantraṃ vyaktaṃ viparītam-avyaktam ||',

'hetumat:원인이 있고',
'anitya: 무상, 영원하지 않음',
'avyāpin: 충만하지 않은, 모든 곳에 있지 않은',
'sakriya: 활동하는, 움직이는',
'aneka: 다수, 무수',
'āśrita: 의존하는, 지배되는',
'liṅga: 표식(표징)하는 것, ',
'sāvayava:부분을 가진, 결합되고',
'paratantra: 의존, 보조적인',
'vyakta: 드러난 것',
'viparīta: 뒤집어진',
'avyakta: 드러나지 않은 것',
],
[
'sk11 드러난 것의 성질:',
'드러난 것은 세 구나이고, 식별 못하고, 대상이고, 공통되고, 알아차리지(감수) 못하고, 산출법칙을 따른다./ 토대(쁘라다나)가 그와 같다. 뿌만(뿌루샤)은 그와 반대이다.',

'(보충설명) ',
'triguṇam-aviveki viṣayaḥ sāmānyam-acetanaṃ prasava-dharmi |vyaktaṃ tathā pradhānaṃ tat-viparitaḥ tathā ca pumān ||',

'triguṇa: 세 구나',
'avivekin:(~i, 중성 단수 주격) 식별 못하는',
'viṣaya: 대상',
'sāmānya: 공통, 똑같음, 비슷',
'acetana:  감수(내관) 못하는, 알아차리지 못하는',
'prasava: 산출, 낳음',
'dharmin: 법칙을 따르는',
'vyakta: 드러난 것(* 앞의 경문10 참조)',
'tathā: 그렇게',
'pradhāna: 토대, 제1원인 ',
'tat: 그',
'viparita: 반대', 
'tathā:그렇게',
'ca:또한',
'pumān: 인간, 영혼, 뿌루샤',
],
[
'sk12 드러난 것의 작용, 세 구나:',
'즐거움, 괴로움, 멍함(망상)으로 구성된 것(구나)들은 광명, 활동, 억제를 위한 것들이다./ 구나들은 상호 지배, 의존, 산출, 결합의 작용들을 한다.',

'(보충설명) ',
'prīti-aprīti-viṣāda-ātmakāḥ prakāśa-pravṛtti-niyamārthāḥ |anyonya-abhibhava-āśraya-janana-mithuna-vṛttayaḥ ca guṇāḥ ||',

'prīti: 즐거움',
'aprīti: 괴로움, 즐거움없음',
'viṣāda: 둔성, 멍함, 망상',
'ātmaka:(~āḥ, 남성복수주격) 구성된',
'prakāśa: 광명',
'pravṛtti: 활동, 일어나는 작용',
'niyama: 억제, 권계',
'artha:(~āḥ, 남성복수주격) 목적',
'anyonya: 서로서로, 상호',
'abhibhava: 지배',
'āśraya: 의존',
'janana: 산출',
'mithuna: 결합',
'vṛtti:(~ayaḥ, 여성복수주격) 작용', 
'ca: 또한',
'guṇa:(~āḥ, 남성복수주격) 구나, 속성',
],
[
'sk13 세 구나:',
'순질(싸뜨바)은 가볍게 올라가려 하고(바라고), 동질(라자스)은 또한 흥분하여 움직이려 하고/ 암질(따마스)은 정말이지 무겁게 가라앉으려 한다. 마치 등불(불꽃, 심지, 기름)처럼 목적성을 위해 작동한다.',

'(보충설명) ',
'sattvaṃ laghu prakāśakam-iṣṭam-upaṣṭambhakaṃ calaṃ ca rajaḥ |guru varaṇakam-eva tamaḥ pradīpavat-ca-arthataḥ vṛttiḥ ||',

'sattva: 싸뜨바, 순질',
'laghu: 가벼움',
'prakāśaka: 광명(성),드러남, 올라감',
'iṣṭa: 바램, 추구',
'upaṣṭambhaka: 흥분',
'cala: 움직임',
'ca: 또한',
'rajas: 라자스, 동질',
'guru: 무거운',
'varaṇaka: 덮인, 들어감',
'eva: 정말이지',
'tamas: 따마스, 암질',
'pradīpavat: 등불처럼',
'ca: 또한',
'arthatas: 목적성, 목적을 위함',
'vṛtti: 작용,작동',
],
[
'sk14 드러나지 않은 것(쁘라끄리띠):',
'식별 못하는 것* 등(드러난 것과 드러나지 않은 것)은, 세 구나로 된 것 때문에, 그(것의) 전도된(잘못된) 인식이 없기 때문에 증명된다./ 드러나지 않은 것*도 결과가 원인의 속성(구나)으로 구성되기 때문에 증명된다.',

'(보충설명) ',
'avivekyādeḥ siddhiḥ tri-guṇyāt-tat-viparyaya-abhāvāt |kāraṇa-guṇa-ātmakatvāt-kāryasya-avyaktam-api siddham ||',

'avivekin: 식별못하는 것 (*경문11 참조)',
'ādi: 등',
'siddhi: 증명, 성취',
'tri:셋',
'guṇya: 다수가 된',
'tat: 그',
'viparyaya: 전도된 인식',
'abhāva: 부재',
'kāraṇa: 원인 ',
'guṇa: 구나, 속성',
'ātmakatvāt: 구성된 것처럼',
'kārya:만들어진, 일어난, 결과',
'avyakta: 드러나지 않은 것(경문2 참조)',
'api: ~도',
'siddha: 증명, 성취',
],
[
'sk15 드러나지않은 것(쁘라끄리띠) 존재증명1:',
'구별되는 것들의 한정으로, 동질성으로, 또한 작용의  능력으로/ 원인결과가 구분되는 것으로, 온세상(다양성)의 구분안되는 것(흡수병합)으로 (드러나지 않은 것의 원인은 있다).',

'(보충설명) ',
'bhedānāṃ parimāṇāt samanvayāt śaktitaḥ pravṛtteḥ ca |kāraṇa-kārya-vibhāgāt-avibhāgāt-vaiśvarūpyasya ||',

'bheda: (~ānāṃ, 복수 속격) 구별, 차이',
'parimāṇa: 측정, 한정',
'samanvaya: 동질성, 연결, 계기',
'śaktitas: 능력, 힘',
'pravṛtti: (~eḥ, 남성 단수 종격속격) 작용, 활동',
'ca: 또한',
'kāraṇa: 원인',
'kārya: 만들어진, 일어난, 결과',
'vibhāga: 구분',
'avibhāga: 구분안됨',
'vaiśvarūpya:온 세상, 다양성, 복수성',
],
[
'sk16 드러나지 않은 것(쁘라끄리띠) 존재증명2:',
'또 드러나지 않은 것의 원인은 세 구나와 결합으로 작동한다./ 물처럼 계속되는 구나의 의존과 분리로. ',

'(보충설명) ',
'kāraṇam-asti-avyaktaṃ pravartate tri-guṇataḥ samudayāt-ca |pariṇāmataḥ salilavat prati-prati-guṇa-āśraya-viśeṣāt ||',

'kāraṇa: 원인',
'asti: 있다',
'avyakta: 드러나지 않은',
'pravartate: 작동한다',
'tri-guṇatas: (*tas는 종격의미를 갖는, 부사를 만드는 접미사) 세 구나로부터',
'samudaya:(~āt, 중성단수종격) 결합',
'ca: 또한',
'pariṇāmata:(~ḥ,*taḥ는 종격의미를 갖는, 부사를 만드는 접미사)  (윤회) 전변으로', 
'salilavat: salila :(*vat은 ~처럼의 뜻을 갖는 접미사) 물, 물살 같은',
'prati prati: 계속해서',
'guṇa: 구나',
'āśraya: 의존',
'viśeṣa:(~āt, 중성단수종격) 분리, 구별, 차이',
],
[
'sk17 뿌루샤 존재 이유:',
'정신(뿌루샤)은 존재한다. 결합된 것들의 초월적 목적성 때문에, 세 구나들의 많은 부분의 지탱 때문에/ (즐거움과 괴로움의) 향수자가 있어야 하기 때문에, 또 활동하는 것들의 독존을 위하여',

'(보충설명) ',
'saṅghāta-para-arthatvāt tri-guṇādi-viparyāt-adhiṣṭhānāt |puruṣaḥ asti bhoktṛbhāvāt kaivalya-arthaṃ pravṛtteḥ ca ||',

'saṅghāta: 결합, 다수',
'para: 다른',
'arthatva :(~āt, 중성단수종격) 목적성, 의미성, 대상성',
'tri-guṇa :세 구나',
'ādi: 시작,  등등, ~들',
'viparya:(~āt, 중성단수종격) 부분, 많은',
'adhiṣṭhāna: (~āt, 중성단수종격) 지지, 지탱',
'puruṣaḥ: 뿌루샤',
'asti: 있다',
'bhoktṛ: (즐거움과 괴로움의) 향수자',
'bhāva :(~āt, 중성단수종격) 있음',
'kaivalya: 독존',
'arthaṃ: ~을 위하여, 목적, 대상',
'pravṛtti: (~eḥ, 여성단수속격)(일어나는) 활동, 작용',
'ca: 또한',
],
[
'sk18 정신 다수성:',
'정신(뿌루샤)의 다수성은 증명된다. 태어나고 죽는 원인들의, 또 바로 비동시적인 작용의 개별법칙(할당) 때문에,/ 또 세 구나로 인한 변화(부분) 때문에.',

'(보충설명) ',
'janana-maraṇa-karaṇānāṃ pratiniyamāt-ayugapat-pravṛtteḥ ca |puruṣa-bahutvaṃ siddhaṃ tri-guṇya-viparyayāt-ca-eva ||',

'janana: 태어나는',
'maraṇa: 죽는',
'karaṇa:(~āṃ, 중성복수속격) 일어나는, 작용하는, 원인, 감각기관',
'pratiniyama:(~āt, 중성단수종격) 개별 법칙, 개별 할당',
'ayugapad:(t) 동시적이 아닌, 비동시적',
'pravṛtti:(~eḥ, 여성단수속격) 활동, 작용',
'ca: 또한',
'puruṣa: 뿌루샤',
'bahutva:(~ṃ, 중성단수주격) 다수성, 복수성',
'siddha:(~ṃ, 중성단수주격) 증명, 확인, 성취 ',
'tri-guṇya: 세 구나',
'viparyaya:(~āt, 중성단수종격) 부분, 많은, 변화',
'ca: 또한',
'eva: 정말이지, 바로',
],
[
'sk19 뿌루샤, 행위하지 않는자:',
'또한 그 반대로부터 이 정신(뿌루샤)의 완성된 증거가/ 독존, 중립, 보는능력, 행위하지 않는자가 (나온다)',

'(보충설명) ',
'tasmāt-ca viparyāsāt siddhaṃ sākṣitvam-asya puruṣasya |kaivalyaṃ mādhyastyaṃ draṣṭṛtvam-akartṛbhāvaḥ ca ||',

'tasmāt:(tad, 남성중성단수종격) 그(드러나지 않은 것)',
'ca: 또한',
'viparyāsa:(~āt, 남성단수종격) 전도, 대조, 반대',
'siddha:(~ṃ, 형용사 중성단수주격) 완성된, 성취된',
'sākṣitva:(~m, 중성단수주격)  증거',
'asya: (idam, 남성중성단수속격) 이것의 ',
'puruṣasya: (남성단수속격) 뿌루샤의, 정신의',
'kaivalya: (~ṃ, 중성단수주격) 독존',
'mādhyastya:(~ṃ, 중성단수주격) 중재, 중립',
'draṣṭṛtva:(~m, 중성단수주격) 보는 능력, 지각',
'akartṛbhāva: (~ḥ, 남성단수주격)  행위하지 않는 존재',
'ca: 또한',
],
[
'sk20 정신 원질 혼동, 무명:',
'그로부터 그 결합으로 감수하지 못하는 것을 감수하는 것처럼 링가(표식, 붓디 이하의 것들)로 (여기고) / 구나가 행위자인 것처럼 그렇게 되고, 또 중립한 자(뿌루샤)도 그렇게 구나 행위자처럼 됩니다.',

'(보충설명) ',
'tasmāt-tat-saṃyogāt-acetanaṃ cetanāvat-iva liṅgam |guṇa-kartṛtve-api tathā karteva bhavati-udāsīnaḥ ||',

'tasmāt: 그러므로, 그로부터',
'tat: 그',
'saṃyogāt: 결합으로',
'acetana:(~m, 중성단수대격) 감수 못함, 내관없음, 의식하지 못함',
'cetanāvat: 감수하는 것처럼, 의식하는 것처럼',
'iva:~처럼',
'liṅga:(~m,  객체(사라지는), 표식, 결과(붓디 이하의 것들)',
'guṇa: 구나',
'kartṛtva: 행위, 행위자성, 행위자로 여김',
'api: ~도',
'tathā: 그렇게 ',
'karta: 행위자',
'iva:처럼',
'bhavati:(bhū, 3인칭단수현재) 있다. 되다',
'udāsīna: 중립한 자, 무심한 자(뿌루샤를 지칭)',
],
[
'sk21 정신 원질 결합:',
'정신(뿌루샤)의 봄(지각)을 위한, 독존을 위한, 마찬가지로 토대(쁘라다나)의 (봄을 위한, 독존을 위한)/ 앉은뱅이와 봉사 같은 그 둘의 결합이 이루어진 창조입니다.',

'(보충설명) ',
'puruṣasya darśana-arthaṃ kaivalya-arthaṃ tathā pradhānasya |paṅgu-andha-vat-ubhayoḥ api saṃyogaḥ tat-kṛtaḥ sargaḥ ||',

'puruṣa: 뿌루샤 ',
'darśana-arthaṃ: 보기 위함 ',
'kaivalya-arthaṃ: 독존을 위함',
'tathā: 그렇게, 마찬가지로',
'pradhānasya: 토대의',
'paṅgu-andha-vat: 앉은뱅이와 봉사 처럼 ',
'ubha :(~yoḥ, 남성양수속격) 양쪽, 둘',
'api:~도',
'saṃyoga:(~ḥ, 남성단수주격) 결합 ',
'tat: 그',
'kṛta:(~ḥ, 남성단수주격) 행해진, 이루어진',
'sarga:(~ḥ, 남성단수주격) (물질의) 창조,', 
],
[
'sk22 창조 16가지 요소:',
'원질(쁘라끄리띠)로부터 마하트(위대한 것, 붓디)가, 그리고 자의식(아함까라)이, 그로부터 또 16가지* 무리들이 (나온다)/ 5가지(색성향미촉, 5유)로부터 5가지 요소(지수화풍공, 5대)들이 (나온다.)',

'(보충설명) *원질(쁘라끄리띠)로부터, 마하트(위대한 것)로 불리는 붓디(지성)과 아함까라(자의식)가 되고, 여기서 다시 16 가지가 된다. 16가지는 색성향미촉의 5 가지 미세원소(5유),  눈귀코혀몸의 5 가지 감각기관, 입, 손, 발, 성기, 항문의 5 가지 행위기관, 그리고 마음(마나스)을 말한다. <br> 그리고 5 가지 미세원소(5유)로부터 5가지 거친 요소, 즉 지수화풍공(5대)이 나온다 ',
'prakṛteḥ mahāṃs tataḥ ahaṃkāraḥ tasmāt-gaṇaḥ ca ṣoḍaśakaḥ |tasmāt-api ṣoḍaśakāḥ pañcabhyaḥ pañca-bhūtāni ||',

'prakṛti: 쁘라끄리띠, 원질 ',
'mahāṃs:mahan : (mahat의 주격) 위대한 것',
'tatas: 거기서',
'ahaṃkāra: 자의식',
'tasmāt: (불변화사) 그로부터',
'gaṇa: 그룹, 일단',
'ca: 또한',
'ṣoḍaśaka: 16',
'tasmāt: 그로부터',
'api:~도, 또한',
'ṣoḍaśaka: 16 ',
'pañca :(~bhyaḥ, 중성복수종격) 5가지',
'pañcabhūtāni := 다섯 요소, 오대(지수화풍공)',
'pañca =:',
'bhūta :(~āni, 중성복수주격) 요소, 존재',
],
[
'sk23 지성 순질 암질:',
'지성(붓디)은 확인(의욕)하는 것이다. 다르마(선), 지혜, 초연한 능력./ 순질(싸뜨바)상태는 이런 형태(모습)이고, 암질(따마사)상태는 이것에서 전도된 것이다. ',

'(보충설명) ',
'adhyavasāyaḥ buddhiḥ dharmaḥ jñānaṃ virāga aiśvaryam |sāttvikam-etad-rūpaṃ tāmasam-asmāt-viparyastam ||',

'adhyavasāya:(~ḥ, 남성단수주격) 확인, 정신적 노력, 의욕',
'buddhi :(~ḥ, 여성단수주격) 붓디, 지성',
'dharma :(~ḥ, 남성단수주격) 다르마, 선',
'jñāna :(~ṃ, 중성단수주격) 지혜',
'virāga: 무관심한, 초연한',
'aiśvarya:(~m, 중성단수주격)초인적 힘, 능력',
'sāttvika:(~m, 중성단수주격) 순질상태',
'etad:(t, 중성단수주격) 이',
'rūpa:(~m, 중성단수주격) 형태, 모습 ',
'tāmasa: (~m, 중성단수주격) 암질, 둔성상태',
'asmāt: 이것으로부터',
'viparyasta:(~m, 중성단수주격) 전도',
],
[
'sk24 자의식에서 16가지가:',
'아함까라는 자기의식이다. 거기서 두 종류의 창조가 진행한다/ 11가지 그룹과 또 미세원소 5 가지의 (그룹이). ',

'(보충설명) ',
'abhimānaḥ ahaṃkāraḥ tasmād dvi[vi]dhaḥ pravartate sargaḥ |ekādaśakaḥ ca gaṇaḥ tanmātraḥ pañcakaḥ ca-eva ||',

'abhimānaḥ: 자기 주장(의식)',
'ahaṃkāraḥ: 아함까라, 자의식',
'tasmād: 거기서',
'dvividhaḥ: 두쌍',
'pravartate:진행',
'sarga: 창조, 일어남',
'ekādaśaka: 11',
'ca  또한',
'gaṇa: 그룹, 무리',
'tanmātra:미세원소', 
'pañcaka: 다섯',
'ca: 또한',
'eva: 바로',
],
[
'sk25 11가지 순질, 5가지 암질:',
'자의식(아함까라)에서 만들어진 11가지(감각)는 순질성이 진행한 것이고/ (5가지) 요소 등의 미세원소, 그것은 암질성이 (진행한 것이다). (이) 두 가지(11가지 감각들과 5가지 미세원소들)는 빛으로 된 것이다.',

'(보충설명) ',
'sāttvikaḥ ekādaśakaḥ pravartate vaikṛtād ahaṃkārāt |bhūtādeḥ tanmātraḥ sa tāmasaḥ taijasād ubhayam ||',

'sāttvika: (~ḥ, 남성단수주격) 순질성',
'ekādaśaka: (~ḥ, 남성단수주격) 11 가지',
'pravartate: (pravṛt, Ā. 3인칭단수현재)진행하다. 나아가다',
'vaikṛta:(~ād, ~āt, 중성단수종격) 변화인, 변화를 일으키는 것(*경문3 참조)',
'ahaṃkāra :(~āt, 남성단수종격) 아함까라에서',
'bhūta: 요소',
'ādi: (~ādeḥ, 여성단수속격) ~등, ~을 비롯해서', 
'tanmātra:(~ḥ, 남성단수주격?) 미세원소',
'sa: (ḥ) 그(것)',
'tāmasa:(~ḥ, 남성단수주격) 암질성',
'taijasa:(~ād, āt, 남성단수종격) 빛으로 된, 빛에서 나온',
'ubhaya:(~m, 중성단수주격) 둘',
],
[
'sk26 감각기관 행위기관:',
'인식(붓디, 지성) 기관들은 눈, 귀, 코, 혀, 피부이고/ 행위(까르마) 기관들은 말(입), 손, 발, 항문, 성기이다. ',

'(보충설명) ',
'buddhi-indriyaṇi cakṣuḥ srotra-ghrāṇa-rasana-tvak-ākhyāni |vāk-pāṇi-pāda-pāyū-upastāḥ karma-indriyāṇi-āhuḥ ||',

'buddhi: 붓디, 지성',
'indriya: 감각기관, 감관',
'cakṣu: 눈 ',
'srotra: 귀',
'ghrāṇa: 코',
'rasana: 혀',
'tvak: 피부',
'ākhyāni: 말해지고',
'vāc: 말',
'pāṇi: 손',
'pāda: 발',
'pāyū: 항문',
'upasta: 성기',
'karma: 까르마, 행위',
'indriya: 감각기관, 감관',
'āhuḥ: 그들은 말한다',
],
[
'sk27 마음, 분별하는 감관:',
'이들 가운데, 두가지(정신, 원질) 본질을 가진 마음은 또한 분별하는 감관이다. (이것도 인식기관 행위기관과) 동질성이지만/ 다양한 구나 전변 차이로 또한 외적 구별들이 있다. (*비갸나 빅슈: 구나 전변으로 차이나는 다양성이 외적구별에서 나온다)',

'(보충설명) ',
'ubhaya-ātmakam-atra manaḥ saṅkalpakam-indriyaṃ ca sādharmyāt |guṇa-pariṇāma-viśeṣāt-nānātvaṃ bāhya-bhedāḥ[bhedāt] ca ||',

'ubhaya: 둘',
'ātmakam: 구성된, 본질을 가진',
'atra: 여기',
'manaḥ: 마음',
'saṅkalpaka: 사고하는',
'indriya: 감각 기관, 감관',
'ca: 또한',
'sādharmya: 동질성, 같은?',
'guṇa: 구나',
'pariṇāma: 전변',
'viśeṣāt: 구별, 차이',
'nānātva: 다양성, 다수성',
'bāhya: 외부',
'bheda: 나눠짐, 구별',
'ca: 또한',
],
[
'sk28 마음작용, 감각기관 행위기관:',
'소리[*형태] 등 (감각기관)에서 5가지 앎(봄)만 얻어지는 것이 (마음)작용이다./ 또한 (행위기관에서) 말, 붙잡음, 걸음, 배출, 환희 등이 (얻어진다).',

'(보충설명) ',
'śabdā[*rūpā]diṣu pañcānām ālocana-mātram-iṣyate vṛttiḥ |vacana-ādāna-viharaṇa-utsarga-ānandāḥ ca pañcānām ||',

'śabdadiṣu: 소리 등에서',
'pañcānām: 5가지의',
'ālocana: 봄, 지각',
'mātra: ~만',
'iṣyate: 얻어진다',
'vṛttiḥ: 작용',
'vacana: 말',
'ādāna: 잡음, 움켜쥠',
'viharaṇa: 걸음, 움직임',
'utsarga: 방출',
'ānandāḥ: 환희 ',
'ca: 또한',
'pañcānām: 다섯가지를',
],
[
'sk29 지성 자의식 마음 기운:',
'그들 셋(내부기관; 붓디, 아함까라, 마나스)은 각자 특징적 작용이 있어, 이것들은 (서로) 다르다/ 공통으로 일어나는 작용은 기운(쁘라나) 등에서 나온 다섯 가지이다. ',

'(보충설명) ',
'svā-lakṣanyaṃ vṛttiḥ trayasya sā-eṣā bhavati-asāmānya |sāmānya-karaṇa-vṛttiḥ prāṇa-ādyā vāyavaḥ pañca ||',

'svā: 자신들',
'lakṣanya: 표시, 특징',
'vṛttiḥ:작용',
'trayasya: 셋의(붓디, 아함까라, 마나스)',
'sā: 같은',
'eṣā:  이것들',
'bhavati: ~이다',
'asāmānya: 공통되지 않음, 다름',
'sāmānya: 공통된',
'karaṇa: 일어나는, 작용하는, 원인, 기관',
'vṛttiḥ: 작용',
'prāṇa-ādyā: 쁘라나 등',
'vāyu: (~avaḥ, 남성 복수 주격) 기운',
'pañca: 다섯(쁘라나, 아빠나, 우다나, 싸마나, 브야나) ',
],
[
'sk30 지성 자의식 마음 감각:',
'그러나 그 제시된 네가지(붓디, 아함까라, 마나스와 하나의 감각)작용은* 동시적(순간적)이고, 또한 계기적이다./ 본것 (지각한것)에서처럼 안본것에서도 세가지(붓디, 아함까라, 마나스)는 그(네번째 지각) 이전에 작용이 (일어난다).*',

'(보충설명)*난다날 신하의 주석은 순간적으로 일어나는 네 작용을 설명한다. 어두운 밤에 갑자기 호랑이를 만났을 때, 눈은 (즉시 물체를) 포착하고, 마음은 그것이 (뭔지) 생각하고, 자의식은 (두려움을) 감지하고, 지성(붓디)는 (도망칠 것을) 판단한다고.',
'yugapat-catuṣṭayasya tu vṛttiḥ kramaśaś-ca tasya nirdiṣṭā |dṛṣṭe tathā-api-adṛṣṭe trayasya tat-pūrvikā vṛttiḥ ||',

'yugapad: 동시적',
'catuṣṭaya:(형용사)넷으로 된, 네 쌍인 (*붓디, 아함까라, 마나스와 하나의 감각)',
'tu: 그러나',
'vṛttiḥ:작용',
'kramaśa: (불변화사) 계기적, 연관적',
'ca: 또한',
'tasya: 그',
'nirdiṣṭa: 알려진, 제시된',
'dṛṣṭe: 본',
'tathā: 그렇게',
'api: ~도',
'adṛṣṭe:  안본',
'trayasya: 셋의',
'tat: 그',
'pūrvikā: 이전, 앞서서',
'vṛttiḥ: 작용',
],
[
'sk31 마음작용, 정신 목적 원인:',
'(감관들은) 각각 상호 목적(자극)을 원인으로 (마음)작용에 이르지만/ 정신(뿌루샤)을 위한 것만이 원인일 뿐이고, 다른 어떤 작용(원인)으로 만들어지는 것이 아니다.',

'(보충설명) ',
'svāṃ svāṃ pratipadyante paraspara-ākuta-hetukāṃ vṛttim |puruṣa-artha eva hetuḥ na kenacit kāryate karaṇam ||',

'svāṃ: 자신',
'svāṃsvāṃ: 각각',
'pratipadyante: 도달하다.',
'paraspara: 상호',
'ākūta: 의도, 목적, 활동에의 자극',
'hetukāṃ: 원인적',
'vṛttim: 작용',
'puruṣa-artha: 뿌루샤 목적',
'eva: 정말이지',
'hetuḥ: 원인',
'na: 아니다',
'kenacit: 어떤 것에 의해서도',
'kāryate: 만들어지다',
'karaṇa: 일어나는, 작용하는, 원인, 감관',
],
[
'sk32 13종 원인기관, 10종 결과:',
'13종의 (원인)기관, 그것은 붙잡음, 응념(유지), 빛을 비춤(드러냄)이다./ 붙잡혀 유지되고 드러난 것이 그 10 가지 (일어난) 결과이다.*',

'(보충설명)*13종의 기관은 내부기관 3가지(붓디, 아함까라, 마나스) 감각기관 5가지(눈 귀 코 혀 피부), 행위기관 5가지(입 손 발 항문 성기)이다. 이것들에 의햇 붙잡혀, 유지되어, 드러난 결과 10가지는 인식기관의 색성향미촉 5가지와 행위기관의 말, 잡음, 이동, 배출, 희열 5가지이다. 이것은 주석자 가우다파다의 해석이다. <br> 주석자 나라야나의 해석은 다르다. 즉 일어난 결과 10가지이다. 즉 붙잡을 수 있는 행위기관(입, 손, 발, 항문, 성기)의 5가지 대상을 인간적인 것과 신적인 것으로 나눈 10가지이다. 3가지 내부기관이 유지하여 드러난 5가지 감각(색성향미촉) 대상도  인간적인 것과 신적인 것으로 나눈 10가지이다. 그러나 베너르지는 이 나라야나의 해석은 후대에 덧보태진 것으로 이해한다.',

'karaṇaṃ trayodaśavidhaṃ tat āharaṇa dhāraṇa prakāśakaram |kāryaṃ ca tasya daśadha āhāryaṃ dhāryaṃ prakāśyaṃ ca ||',

'karaṇa: 일어나는, 작용하는, 원인, 기관 ',
'trayodaśavidhaṃ:13 쌍',
'tat: 그',
'āharaṇa: 포착, 붙잡음',
'dhāraṇa: 응념, 집중 ',
'prakāśa: (빛을)비추는',
'kara: 행위, 행위자, 작용',
'kārya: 만들어진, 일어난, 결과 ',
'ca: 또한',
'tasya: 그의',
'daśadha: 열쌍',
'āhārya: 포착된 것',
'dhārya: 응념 것',
'prakāśya:비춰진 것',
'ca: 또한',
],
[
'sk33 내부기관 외부기관 시간:',
'내부기관은 세 가지(붓디, 아함까라, 마나스)이다. 외부(기관)은 10 가지이고, 그(내부기관의) 대상이라고 말해진다./ 외부기관은 현재 시간이고, 내부(기관)는 세 시간(과거, 현재, 미래)이다.',

'(보충설명) ',
'antaḥ karaṇaṃ trividhaṃ daśadhā bāhyaṃ trayasya viṣayākhyam |sāmpratakālaṃ bāhyaṃ trikālam ābhyantaraṃ karaṇam ||',

'antaḥ: 내부',
'karaṇa: 일어나는, 원인, 기관',
'trividhaṃ: 세 쌍',
'daśadhā: 10 쌍',
'bāhyaṃ: 외부',
'trayasya:셋',
'viṣaya: 대상',
'ākhya: 일컬어지는, 불리는',
'sāmprata: 현재',
'kālaṃ: 시간 ',
'bāhyaṃ: 외부',
'trikālam: 세 시간',
'ābhyantaraṃ: 내부',
'karaṇam: 일어나는, 원인, 원인기관',
],
[
'sk34 붓디 감각 구별되는 것, 말 소리:',
'그들 가운데서 인식(붓디) 기관들은 다섯 가지 구별되거나(거친)/ 구별안되는(미세한)* 대상들이다. / (행위 기관들은) 말은 소리만 대상이지만, 그러나 나머지 것들은 다섯 대상들이다.*',

'(보충설명) ',
'buddhi indriyāṇi teṣāṃ pañca viśeṣa aviśeṣa viṣayāṇi |vāk bhavati śabda viṣayā śeṣāṇi tu pañca viṣayāṇi ||',

'buddhi: 붓디, 지성',
'indriya:(~āṇi, 복수) 감각, 감관, 기관',
'teṣāṃ: 그들의',
'pañca: 다섯',
'viśeṣa: 구별되는것(거친것)',
'aviśeṣa: 구별안되는것(미세한것)(*보통 인간의 감관으로는  구별 안되지만, 신이나 요가를 성취한 자들에 의해 구별되는 것을 말한다.)',
'viṣayāṇi: 대상들',
'vāk: 말',
'bhavati: 되다', 
'śabda: 소리',
'viṣayā: 대상',
'śeṣāṇi: 나머지 것들(*말은 소리만 대상이지만, 나머지 것들은 다섯 대상들이다*는 것을 신하 난다랄의 주석은 이렇게 설명한다. 손으로 항아리 같은 것을 잡거나, 발로 땅을 밟거나, 배설하거나, 성행위를 하게 되면, 색성향미촉 다섯 가지 감각들이 함께 관련된다고 한다.)',
'tu: 그러나',
'pañca: 다섯',
'viṣayāṇi: 대상들',
],
[
'sk35 내부기관 문지기 외부기관 문들:',
'그 내부 인식 기관(붓디, 아함까라, 마나스)이 모든 대상을 이해한다/ 그러므로 세 가지 기관은 문지기이고, 다른 것들은 문들이다. ',

'(보충설명) ',
'śāntaḥ karaṇaṃ buddhiḥ sarvaṃ viṣayam avagāhate yasmāt |tasmāt trividhaṃ karaṇaṃ dvāri dvārāṇi śeṣāṇi ||',

'śāntaḥ: sa + antah:  그 내부의 것',
'karaṇa: 일어나는, 작용하는, 원인, 기관',
'buddhiḥ: 붓디, 지성',
'sarvaṃ: 모두',
'viṣayam: 대상',
'avagāhate: 이해',
'yasmāt: ',
'tasmāt: 그것에서',
'trividhaṃ: 세 쌍',
'karaṇa: 일어나는, 작용하는, 원인, 기관',
'dvārin: 지키는 자, 문지기',
'dvāra: (~āṇi, 복수 주격) 문들',
'śeṣāṇi: 남은 것들',
],
[
'sk36 정신 목적 광명 지성:',
'이들의 서로서로 다른 차이들은 등불과 유사한 구나의 구별들이다./ 정신(뿌루샤)을 위해 모두가 광명의 지성(붓디)에 보여진다.',

'(보충설명) ',
'ete pradīpakalpāḥ paraspara vilakṣaṇāḥ guṇa viśeṣāḥ |kṛts[n]aṃ puruṣayā arthaṃ prakāśya buddhau prayacchanti ||',

'ete: 이들(*10가지 외부 감각기관들과 아함까라 마나스의 12가지)',
'pradīpa: 등불',
'kalpa: 유사, 비유 ',
'paraspara: 서로, 각각',
'vilakṣaṇa: 구별되는 차이',
'guṇa: 구나',
'viśeṣāḥ: 구별들',
'kṛtsnaṃ: 전체',
'puruṣayā: 뿌루샤를 위한',
'arthaṃ: 위함, 목적',
'prakāśya: 광명, 드러남',
'buddhau: 붓디에서',
'prayacchanti: prayam, 제공한다. 보여진다. 드러난다',
],
[
'sk37 정신 목적 토대 식별:',
'모든 관련된 경험은 정신(뿌루샤)의(을 위해) 지성(붓디)가 일어난 것이다./ 그것(붓디)은 또한 정말이지 토대와 뿌루샤의 다름을 미세하게 식별한다.',

'(보충설명) ',
'sarvaṃ prati upabhogaṃ yasmāt puruṣasya sādhayati buddhiḥ |sa eva ca viśinaṣṭi punaḥ pradhāna puruṣāṅtaraṃ sūkṣmam ||',

'sarva: 모든',
'prati: ~관해',
'upabhoga: (결합을 통한) 경험 ',
'yasmāt:',
'puruṣasya: 뿌루샤의 ',
'sādhayati: 일어나다. ',
'buddhiḥ: 붓디, 지성',
'sā: 그녀(붓디)',
'eva: 정말',
'ca: 또한',
'viśinaṣṭi: 원형',
'viśiṣ: 식별하다, 구별하다',
'punaḥ: 다시',
'pradhāna: 토대 ',
'puruṣa: 뿌루샤',
'aṅtara: 다름, 내부',
'sūkṣma: 미세',
],
[
'sk38 미세원소 거친요소:',
'미세원소들은 구별되지 않는다. 그것(미세원소)들에서 다섯 거친요소들이 나왔다. 다섯 가지로부터 (나온)/ 이들은 평온함들, 두려움들, 그리고 어리석음들이 기억되고 구별된다.',

'(보충설명) ',
'tanmātrāṇi aviśeṣāḥ tebhyo bhūtāni pañca pañcabhyaḥ |ete smṛtāḥ viśeṣāḥ śāṅtāḥ ghorāḥ ca mūḍhāḥ ca ||',

'tanmātra: 미세원소, 5유',
'aviśeṣa: 구별되지 않음(앞의 경문34 참조)',
'tebhyo:(tebhyah, tad의 복수 종격) 그것들에서',
'bhūta: 요소',
'pañca: 다섯',
'pañcabhyaḥ: 다섯에서',
'ete: 이들이',
'smṛtāḥ: 기억들 ',
'viśeṣāḥ: 구별된 것들',
'śāṅta: 평온, (즐거움)',
'ghora: 두려움, (고통)',
'ca: 또한',
'mūḍha: 어리석음, (멍함)',
],
[
'sk39 미세한 것들, 거친 것들, 윤회:',
'미세한 것들은 어머니아버지가 낳은 거친요소들과 함께 세쌍(평온함, 두려움, 어리석음)의 구별되는 것들이 된다/ 미세한 그것들은 이어진다. 어머니아버지가 낳은 것(거친 것)들은 멈춘다. ',

'(보충설명) ',
'sūkṣmāḥ mātāpitṛjāḥ saha prabhūtaiḥ tridhā viśeṣāḥ syuḥ |sūkṣmāḥ teṣāṃ niyatāḥ mātā pitṛjāḥ nivartaṇte ||',

'sūkṣmāḥ: 미세한 것들',
'mātā pitṛ jāḥ:어머니 아버지가 낳은 것들',
'saha: 함께',
'prabhūtaiḥ: 거친 요소들로',
'tridhā: 세쌍 (앞에서 말한 평온함, 두려움(고통), 어리석음)',
'viśeṣāḥ: 구별되는 것들',
'syuḥ:~될 것이다. 된다.',
'sūkṣmāḥ: 미세한 것들',
'teṣāṃ: 그들',
'niyatāḥ: 이어지는 것들',
'mātā pitṛ jāḥ: 어머니 아버지가 낳은 것들', 
'nivartaṇte: 멈춘다, 되돌아간다.',
],
[
'sk40 미세한 것, 링가 윤회:',
'시초에 일어난, 멈추지 않는, 항구적인, 마하트(붓디, 지성) 등에서  미세한 것(오유)까지/ 즐거움없는(경험이 결여된) 상태(조건)로  물들여진 링가(표식만 있는 것, 미세몸)는 윤회한다. ',

'(보충설명) ',
'pūrva-utpannam asaktaṃ niyatam mahat ādi sūkṣma-paryaṇtam |saṃsarati nirupa-bhogaṃ bhāvaiḥ adhivāsitaṃ liṅgam ||',

'pūrva: 시초, 처음',
'utpanna: 일어남',
'asaktaṃ: 멈추지 않음',
'niyatam: 항구적인',
'mahat: 큰, 위대한',
'ādi: 등',
'sūkṣma: 미세',
'paryan[ṇ]ta: 끝나는, 완전히, 극도로 ',
'saṃsarati: 윤회하다',
'nir-upabhoga: 즐거움 없는',
'bhāvaiḥ: 상태,조건으로',
'adhivāsita: 물들여진, 채색된',
'liṅga: 표식, 미세몸',
],
[
'sk41 토대 링가 식별:',
'바탕 없는 그림이나, 기둥 같은 것 없는 그림자처럼/ 그렇게 링가도 바탕없이는 구별되는 것이 없어 설 수가 없다. ',

'(보충설명) ',
'citraṃ yathā āśrayam ṛte sthāṇvādibhyo vinā yathā chāyā |tadvat vinā viśeṣaiḥ na tiṣṭhati nirāśrayaṃ liṅgam ||',

'citra: 그림, 잘보이는 ',
'yathā: 처럼',
'āśraya:  바탕, 토대',
'ṛte:  ~없이',
'sthāṇu: 기둥',
'ādibhyo: ~등으로부터',
'vinā: 없이',
'yathā: 처럼',
'chāyā: 그림자, 그늘',
'tadvat: 그처럼',
'vinā: 없이',
'viśeṣaiḥ: 구별, 구별되는 것',
'na ',
'tiṣṭhati: 서다, 지탱하다',
'nirāśrayaṃ: 바탕 없이, 토대 없이',
'liṅgam: 링가',
],
[
'sk42 정신 목적 원인성 결합 링가:',
'정신(뿌루샤) 목적의 원인성(동기)은 이 니밋따(동력인, 수단)와 나이밋띠까(과보,결과) 연합에 의해/ 원질(쁘라끄리띠)의 모든 가능한 결합이 되고, 링가(미세몸)는 드라마 배우처럼 역할한다.',

'(보충설명) ',
'puruṣārtha-hetukam idaṃ nimitta naimittika prasaṅgena |prakṛteḥ vibhutva yogat naṭavat vyavatiṣṭhate liṅgam ||',

'puruṣa: 뿌루샤, 정신',
'artha: 목적',
'hetukam: 원인 , 동기',
'idaṃ: 이것',
'nimitta: (선 악 같은) 원인성, 동력인',
'naimittika: (신, 인간, 동물 같은) 과보성',
'prasaṅgena: 연합에 의해서',
'prakṛteḥ: 쁘라끄리띠의 ',
'vibhutva: 모든 곳에서, 모든 능력',
'yogat: 결합으로',
'naṭavat: 드라마 배우처럼',
'vyavatiṣṭhate: (원형 sthA) 역할한다',
'liṅga: 링가, 표식, 미세몸',
],
[
'sk43 원인 결과 인과:',
'선(다르마) 등의 성향들은 초월적이고, 원질적이고, 획득된(전변한) 것들이다. / 본(지각한) 것들은 (일어나는) 원인에 얽힌 것이고, 태아 등은 또한 (작용한) 결과에 얽힌 것이다. ',

'(보충설명) ',
'sāṃsiddhikāḥ ca bhāvāḥ prakṛtikāḥ vaikṛtikāḥ ca dharmādyāḥ |dṛṣṭāḥ karaṇāśrayiṇaḥ kāryāśrayiṇaḥ ca kalalādyāḥ ||',

'sāṃsiddhika:(~āḥ, 복수 주격) 내재적, 초월적',
'ca: 또한',
'bhāva:(~āḥ, 복수 주격) 성향, 출현, 존재',
'prakṛtikāḥ: 원질적, 쁘라끄리띠에서 나온, 필수적.',
'vaikṛtikāḥ: 획득된 것, 전변한 것',
'ca:또한',
'dharmādyāḥ: 다르마(선) 등은',
'dṛṣṭāḥ: 본(지각한) 것들, 붓디들?',
'karaṇāśrayiṇaḥ: (일어나는) 원인에 얽힌 것',
'kāryāśrayiṇaḥ: (작용한) 결과에 얽힌 것',
'ca:또한',
'kalalādyāḥ: 태아 등',
],
[
'sk44 선 불선 지혜 식별:',
'선(다르마)으로 위로 올라가고, 불선(아다르마)으로 아래로 내려간다./ 앎(식별지)으로 또한 (무지에) 묶여있는 전도된 것에서 벗어난다. ',

'(보충설명) ',
'dharmeṇa gamanam ūrdhva gamanam adhastād bhavati adharmeṇa |jñānena ca apavargaḥ viparyayāt iṣyate bandhaḥ ||',

'dharmeṇa:다르마(선)으로',
'gamanam: 감',
'ūrdhva: 위로',
'gamanam:감',
'adhastād:adhastāt:  아래로',
'bhavati: 되다. 이다',
'adharmeṇa:다르마 아닌 것(불선)으로',
'jñānena: 지혜로',
'ca: 또한',
'apavargaḥ: 놓여남',
'viparyayāt: 전도로부터',
'iṣyate: 생각되다, 여겨지다.',
'bandhaḥ: 묶임',
],
[
'sk45 욕망 원질 융합 윤회:',
'욕망에서 벗어남(욕망포기)으로 원질(쁘라끄리띠)에 융합한다. 동질(라자스)의 욕망으로 윤회가 있다./ 이쉬와라 힘으로 장애가 없어지고, 그 전도된 것(이쉬와라 힘이 없는, 무력)으로 전도됨(장애)이 있다.',

'(보충설명) ',
'vairāgya[ā]t prakṛtilayaḥ saṃsāro bhavati rājasāt rāgāt |aiśvaryāt avighātaḥ viparyayāt tad viparyāsaḥ ||',

'vairāgya:(~āt, 종격) 욕망에서 벗어남, 욕망포기',
'prakṛtilayaḥ: 쁘라끄리띠 융합',
'saṃsāra: 윤회',
'bhavati: 되다, 이다',
'rājasa: (~āt, 종격) 라자스로, 동질로, 열정으로',
'rāga: 욕망',
'aiśvarya: (~āt, 종격)절대자의 힘, 이쉬와라가 된 상태',
'avighātaḥ: 파괴 되지 않음, 장애없는',
'viparyaya:(~āt, 종격) 전도',
'tad: 그',
'viparyāsaḥ: 뒤집어짐, 반대되는 것, 실수',
],
[
'sk46 현재생각 창조 50가지:',
'이 현재생각(붓디) 일어남(창조)이 전도(무지), 무력(무능), 만족, 성취라는 말이다./ 구나 다양성의 얽힘으로 그 구별들은 50 가지이다.',

'(보충설명) ',
'eṣah pratyayasargaḥ viparyaya-aśakti tuṣṭiḥ siddhi-ākhyaḥ |guṇa-vaiṣamya-vimardāt tasya ca bhedāḥ tu pāñcāśat ||',

'eṣah: 이것',
'pratyaya: 현재생각, 붓디?',
'sargaḥ: 일어남, 창조',
'viparyaya: 전도(무지)',
'aśakti: 무력, 장애',
'tuṣṭiḥ: (자기) 만족',
'siddhi: 성취',
'ākhya: 말, 봄 ',
'guṇa:구나',
'vaiṣamya: 불균등, 다양성',
'vimardāt: 갈등으로부터, 얽힘으로부터 ',
'tasya: 그',
'ca:또한',
'bhedāḥ: 다름, 구별, 종류, 영역',
'tu: 그러나',
'pāñcāśat: 50',
],
[
'sk47 전도 만족 무력 성취:',
'전도(무지) 5 종류 구별들이 있고, 무력(장애) 또한 무능에서 일어난 원인으로/ 28 종류, 만족  9 종류, 성취 8 종류의 구별들이 있다.',

'(보충설명) ',
'pañca viparyaya bhedāḥ bhavaṅti aśaktiḥ ca karaṇa vaikalyāt |aṣṭāvimśāti bhedāḥ tuṣṭiḥ navadhā aṣṭadhā siddhiḥ ||',

'pañca: 다섯, (무지, 자의식, 욕망, 혐오, 생명욕) ',
'viparyaya: 전도',
'bhedāḥ: 다름, 구별',
'bhavaṅti: 이다. 되다',
'aśaktiḥ: 무력, 무능, 장애',
'ca: 또한',
'karaṇa: 일어나는, 작용하는, 원인, 기관',
'vaikalyāt: 무능, 결점으로부터',
'aṣṭā: 8',
'vimśāti: 20',
'bhedāḥ: 구별, 다름',
'tuṣṭiḥ: 만족, 자기도취',
'navadhā: 9쌍',
'aṣṭadhā:8쌍',
'siddhiḥ 성취',
],
[
'sk48 무명 욕망 혐오 생명욕:',
'어둠(무명)* 구별 8 종류, 망상(자의식)*도 또한 (8종류이고), 대망상(욕망)*은 10 종류이다/ 분노(혐오)* 18 종류, 생명욕*도 그렇게(18 종류) 있다.',

'(보충설명) ',
'bhedaḥ tamasaḥ aṣṭa vidhaḥ mohas[a]ya ca daśavidhaḥ maha-mohaḥ |tāmisraḥ aṣṭādaśadhā tathā bhavati aṅdhatā misraḥ ||',

'bhedaḥ:구별',
'tamas:(~ah, 속격) 어둠, 무명(Sinha의 주석에 의하면 무명(아비드야)를 가르킴)',
'aṣṭa: 8',
'vidhaḥ: 종류',
'moha: (~sya, 속격) 망상 (*Sinha의 주석에 의하면, 자아의식(아스미따)를 가리킴)',
'ca ',
'daśavidhaḥ: 10 종류',
'maha-mohaḥ: 대망상(Sinha의 주석에 의하면 욕망(라가)를 가르침것)',
'tāmisraḥ: 혐오(*Sinha의 주석에 의하면 혐오(드베샤)를 가르킴)',
'aṣṭādaśadhā: 18 쌍',
'tathā: 그렇게',
'bhavati: 이다',
'aṅdhatāmisraḥ: 생명욕(*Sinha의 주석에 의하면 생명욕(아비니베샤)를 가르킴) ',
],
[
'sk49 11가지 감각소멸 17가지 지성소멸 무력:',
'11가지 감각결함과 함께 지성(붓디)결함으로 무력(장애)은 일어난다/ 붓디결함들은 17가지로, 만족과 성취가  전도(잘못)된 것이다.',

'(보충설명) ',
'ekādaśa iṅdriyavadhāḥ saha buddhi vadhaiḥ aśaktiḥ uddiṣṭā |saptadaśa vadhāḥ buddheḥ viparyayāt tuṣṭi siddhīnām ||',

'ekādaśa:11(*5감각기관, 5행위기관 그리고 마음의 결함)',
'iṅdriya: 감각',
'vadhāḥ: 결함, 소멸, 파괴',
'saha: 함께',
'buddhi: 붓디, 지성',
'vadhaiḥ: 소멸로',
'aśaktiḥ: 무력',
'uddiṣṭā: 선언됨, 일어난다',
'saptadaśa: 17 (*9가지 만족의 결함과 8가지 성취 결함.바로 다음 경문에서 설명)',
'vadhāḥ: 결함, 소멸, 파괴',
'buddheḥ: 붓디의, 지성의 ',
'viparyayāt: 전도, 잘못됨',
'tuṣṭi: 자기 만족, 도취',
'siddhīnām: 성취들의',
],
[
'sk50 만족 내부적 4가지 외부적 5가지:',
'내부적인 것들 4가지는, 원질(쁘라끄리띠), 일어난 것(물질), 시간, 행운이다.(라 말해진다)/ 대상에서 제어된(멈춰진) 외부적인 것들은 5가지다. (모두) 9 가지 만족들이 선언되었다.(*앞의 경문47 참조)',

'(보충설명) ',
'ādhyātmikāḥ catasraḥ prakṛti upādāna kāla bhāgya ākhyāḥ |bāhyāḥ viṣaya uparamāt pañca nava tuṣṭayaḥ abhimatāḥ ||',

'ādhyātmikāḥ: 내부적인 것',
'catasraḥ: 4',
'prakṛti: 쁘라끄리띠, 원질',
'upādāna: 지각하는, 알아차리는, 물질을 지칭',
'kāla: 시간',
'bhāgya: 행운',
'ākhyāḥ: 불리는 것들',
'bāhyāḥ: 외부 것들',
'viṣaya: 대상',
'uparamāt: 제어된?, 멈춤, 죽음으로',
'pañca:5',
'nava: 9',
'tuṣṭayaḥ: 만족들',
'abhimatāḥ: 선언된 것들',
],
[
'sk51 8가지 성취:',
'숙고, 성언, 독송, 세가지 고통에서 벗어남, 도반 획득 / 보시(정화) 등이 8가지 성취이고, 성취 전의  고리(방해?)는 세 종류이다.(*세 종류: 무지, 무능, 만족)',

'(보충설명) ',
'ūhaḥ śabdaḥ adhyayanaṃ duhkha-vighātāḥ trayaḥ sukṛt prāptiḥ |dānaṃ ca siddhayaḥ aṣṭau siddheḥ pūrvaḥ aṅkuśaḥ trividhaḥ ||',

'ūhaḥ: 숙고',
'śabdaḥ: 말, 성언?',
'adhyayana: 공부, 독송?',
'duhkha: 고통',
'vighātāḥ: 벗어남, 방지',
'trayaḥ: 셋 (* 세가지는 내적, 외적, 신적 고통, 경문1 참조)',
'sukṛt: 선행, 선한 사람(친구), 행운',
'prāptiḥ: 획득',
'dāna: 보시, 자선, 정화',
'ca: 또한',
'siddhayaḥ: 성취들은',
'aṣṭau: 8',
'siddheḥ: 성취의',
'pūrvaḥ: 앞의',
'aṅkuśaḥ: (코끼리 제어하는)고리(방해?), 막대기',
'trividhaḥ:세 종류',
],
[
'sk52 바바(존재) 링가(표식):',
'바바(붓디의 주관적 출현) 없이 링가(딴마뜨라의 객관적인 표식, 미세몸) 없고, 링가 없이 바바는 작용하지 않는다/ 링가로 인한 바바라고 말해지기 때문에 두 쌍의 창조가 진행된다. ',

'(보충설명) ',
'na vinā bhāvaiḥ liṅgaṃ na vinā liṅgena bhāva nirvṛttiḥ |liṅgena bhāvākhyaḥ tasmāt dvedhā pravartate sargaḥ ||',

'na: 아니다',
'vinā: 없이',
'bhāva: 바바, (붓디의 주관적인) 출현,  존재',
'liṅgaṃ: 링가, (딴마뜨라의 객관적인) 표식, 미세몸',
'na: 아니다',
'vinā: 없이',
'liṅga: 링가, 표식',
'bhāva:바바, 성향, 존재, 출현',
'nirvṛttiḥ: 멈춤',
'liṅgena:링가',
'bhāva: 바바',
'ākhya:말해짐',
'tasmāt: 거기서',
'dvedhā: 두쌍',
'pravartate: 진행한다',
'sargaḥ: 창조, 일어남',
],
[
'sk53 8종 신,  5종 기는 것, 인간 한 종, 창조:',
'신은 8 분류이고, 기는 것은 5 종류가 있다/ 인간은 한 종류이다. 간단히 (말해서) [이것이]  (물질적) 요소들의 창조이다.  ',

'(보충설명) ',
'aṣṭa vikalpaḥ daivaḥ tairyagyonaḥ ca pañcadhā bhavati |mānuṣakaḥ ca eka vidhaḥ samāsataḥ (ayam) bhautikaḥ sargaḥ ||',

'aṣṭa: 8  (*8 분류 신들: 브라흐만, 쁘라자빠띠, 인드라, 삐뜨르, 간다르바, 약샤, 락사사,삐샤짜)',
'vikalpaḥ: 분별(망상), 분류',
'daivaḥ: 신들은',
'tairyagyonaḥ: 기는 존재들',
'ca:또한',
'pañcadhā: 5 종류(*기는 것들 5종류: 소, 양, 새, 양서류, 못움직이는 것들)',
'bhavati: 됨, 존재',
'mānuṣakaḥ: 인간',
'ca: 또한',
'eka: 하나',
'vidhaḥ: 종류',
'samāsatas: 간단히',
'bhautikaḥ: (물질적) 요소들',
'sargaḥ: 창조',
],
[
'sk54 구나 순질 암질 동질:',
'위는 순질(쌋뜨바)이 주도적이고, 아래는 암질(따마스)이 주도적이며/ 중간은 동질(라자스)이 주도적이다. 브라흐마를 시작으로 숲의 것(풀잎?)까지이다. ',

'(보충설명) ',
'ūrdhvaṃ sattva-viśālaḥ tamo-viśālaḥ ca mūlataḥ sargaḥ |madhye rajo-viśālaḥ brahmādi stamba-paryaṅtaḥ ||',

'ūrdhvaṃ: 위(신들의)',
'sattva-viśālaḥ: 싸뜨바가 주도적인',
'tamo-viśālaḥ: 따마스가 주도적인',
'ca: ',
'mūlataḥ: 바탕 , 아래',
'sargaḥ: 창조',
'madhye: 중간',
'rajo-viśālaḥ: 라자스가 주도적인',
'brahma: 브라만',
'ādi: 시작',
'stamba: 숲, 일단',
'paryaṅtaḥ: 끝, 풀잎?',
],
[
'sk55 정신 링가작용 내재적고통:',
'거기서 내관(감수)하는 정신(뿌루샤)은 늙고 죽는 활동의 고통을 경험한다./ 링가(미세몸)의 멈추지 않는 작용 때문에 내재적(본질적)인 고통이 있다.',

'(보충설명) ',
'tatra jarāmaraṇa kṛtaṃ duḥkhaṃ prāpnoti cetanaḥ puruṣaḥ |liṅgasya avinivṛtteḥ tasmāt duḥkhaṃ svabhāvena ||',

'tatra: 그곳(*위, 아래, 중간 세상)',
'jarā: 늙음',
'maraṇa: 죽음 ',
'kṛtaṃ: 행해지는, 활동',
'duḥkhaṃ: 고통',
'prāpnoti: 경험하다',
'cetana: 내관, 마음, 감수',
'puruṣaḥ: 뿌루샤',
'liṅgasya:링가의',
'avinivṛtteḥ: 멈추지 않는',
'tasmāt: 거기서',
'duḥkhaṃ: 고통',
'svabhāva: 본성적, 내재적',
],
[
'sk56 개별 정신 해방 목적 창조:',
'이렇게 이것은 마하뜨(위대한 것, 붓디)를 시작으로 요소(오대)끝까지 원질(쁘라끄리띠)에서 만들어진 것이고 / 타자를 위한 창조, 개별 정신(뿌루샤) 해방 목적을, 자신의 목적처럼 여긴다.',

'(보충설명) ',
'ityeṣaḥ prakṛti kṛtaḥ mahadādi viśeṣa bhūta paryantaḥ |prati puruṣa vimokṣārthaṃ svārthe iva pararthe ārambhaḥ ||',

'iti: 이렇게, 이래서',
'eṣaḥ: 이것',
'prakṛti: 쁘라끄리띠',
'kṛtaḥ: 행위',
'mahad, mahat: 마하트',
'ādi: 시작',
'viśeṣa: 구별, 다름, 특수, 개별',
'bhūta: 요소',
'paryantaḥ: 끝까지',
'prati: 개별',
'puruṣa: 뿌루샤',
'vimokṣa: 해방',
'arthaṃ: 목적',
'svārthe: 자신의 목적',
'iva: 인것처럼',
'pararthe: 다른 사람의 목적',
'ārambhaḥ: 창조',
],
[
'sk57 송아지 우유 비유 정신 해방:',
'의식없이 작용하는 우유가 송아지 성장의 원동력(니미따)인 것처럼/ 토대(쁘라다나) 작용이 정신(뿌루샤) 해방의 원동력이다',

'(보충설명) ',
'vatsa vivṛddhi nimittaṃ kṣīrasya yathā pravṛttiḥ ajñasya |puruṣa vimokṣa nimittaṃ tathā pravṛttiḥ pradhānasya ||',

'vatsa: 송아지',
'vivṛddhi: 개발, 성장',
'nimittaṃ: 원동력, 원인, 수단',
'kṣīrasya: 우유의',
'yathā ',
'pravṛttiḥ: 작용',
'ajñasya: 의식없는',
'puruṣa: 뿌루샤',
'vimokṣa: 해방',
'nimittaṃ: 원인, 수단',
'tathā: 그렇게',
'pravṛttiḥ: 작용',
'pradhānasya: 토대',
],
[
'sk58 원질은 정신 해방을 위해 작동:',
'멈춤(해방)을 위한 념원이 인간세상 실천에 작동하는 것처럼/ 드러나지 않은 것(쁘라끄리띠)이 정신(뿌루샤)의 해방을 위해 그처럼 작동한다.  ',

'(보충설명) ',
'autsukya nivṛtti-arthaṃ yathā kriyasu pravartate lokaḥ |puruṣasya vimokṣārthaṃ pravartate tadvat avyaktam ||',

'autsukya: 기대, 바램, 념원',
'nivṛtti: 멈춤, 돌아감',
'arthaṃ: 목적, 위함',
'yathā: 그렇게',
'kriyasu: 실천에',
'pravartate: 활력을 준다, 작동한다',
'lokaḥ: 인간, 세상',
'puruṣa: 정신, 순수 정신',
'vimokṣa: 해방',
'arthaṃ: 목적, 위함',
'pravartate: 활력을 준다, 작동한다',
'tadvat: 그처럼',
'avyaktam: 드러나지 않은 것(쁘라끄리띠)',
],
[
'sk59 원질 무대 댄서:',
'무대에 보여지고 나서 사라지는 댄서처럼/ 정신(뿌루샤)에게 자신을 드러내고 사라지는 것이 원질(쁘라끄리띠)이다.',

'(보충설명) ',
'raṅgasya darśayitvā nivartate nartakī yathā nṛtyāt |puruṣasya tathā ātmānaṃ prakāśya vinivartate prakṛtiḥ ||',

'raṅgasya: 무대',
'darśayitvā: 보여지고서',
'nivartate: 죽다. 사라지다.',
'nartakī: 댄서',
'yathā: 그처럼',
'nṛtyāt: 춤추다',
'puruṣasya: 뿌루샤',
'tathā: 그처럼',
'ātmānaṃ: 자신의 ',
'prakāśya: 드러냄',
'vinivartate: 죽다. 사라지다.',
'prakṛtiḥ: 쁘라끄리띠',
],
[
'sk60 원질, 정신의 목적 추구:',
'(쁘라끄리띠는) 많은 수단들로, (자신에게는) 도움이 안되지만, 영혼(뿜사, 뿌루사)을 돕는다/ 구나를 가진 (쁘라끄리띠는) 구나 없는 존재의 그 목적을 (자신에게는) 의미없이 추구한다.',

'(보충설명) ',
'nanavidhaiḥ upāyaiḥ upakāriṇi anupakāriṇaḥ puṃsaḥ |guṇavati aguṇasya sataḥ tasya artham apārthakaṃ carati ||',

'nanavidha: (~iḥ, 복수 구격) 많은',
'upāya: (~iḥ, 복수 구격) 수단',
'upakārin:(~ṇi, 단수 처격, 복수 주대격) 이로움, 도움',
'anupakārin: (an+ ~ṇaḥ, 단수 종격속격)이롭지 않은, 도움 안되는',
'puṃs: (~aḥ, 남성 단수 종격속격) 뿌루샤, 사람, 영혼',
'guṇavati: 구나를 가진',
'aguṇasya: 구나가 없는',
'sat: (~aḥ, 남성 단수 종격속격) 존재의 ',
'tasya: 그',
'artham: 목적',
'apārthaka:apa+artha +ka, 의미없이, 쓸데없이',
'carati: 추구하다. 움직이다. 활동하다',
],
[
'sk61 정신 모습을 봄, 원질 최고의 활동:',
'원질(쁘라끄리띠)이, 나는 정신(뿌루샤)의 모습을 본다(고 여기)는 것보다/ 그녀(쁘라끄리띠)가, 더 우아한 어떤 것도 다시 획득하는 일은 없다는 것이, 나의 의견이다.',

'(보충설명) ',
'prakṛteḥ sukumārataraṃ na kiñcit asti iti me matiḥ bhavati |yā dṛṣṭā asmi iti punaḥ na darśanam upaiti puruṣasya ||',

'prakṛti: (~eḥ, 중성 단수 종격속격) 쁘라끄리띠 보다',
'sukumāratara: 더 우아한, 더 고결한',
'na: 아니다',
'kiñcit: 누구도',
'asti: 이다',
'iti: 하고',
'me: 나의',
'mati: (~ḥ, 여성 단수 주격) 의견, 생각',
'bhavati: 이다. 되다',
'yā: (yad의 여성 단수 주격) *쁘라끄리띠를 가르킴',
'dṛṣṭā: 본',
'asmi: (나는)~이다.',
'iti: 라고',
'punaḥ: 다시',
'na: 아니다',
'darśana: (~m, 대격) 봄, 모습',
'upaiti: (upa+i, upe) 다가가다. 획득하다.',
'puruṣa: (~sya, 남성 단수 속격) 뿌루샤',
],
[
'sk62 정신 원질 차이:',
'그러므로 그(뿌루샤)는 묶이지도 않고, 해방되지도 않고, 또한 윤회하지도 않는다/ 원질(쁘라끄리띠)은 다양하게 결합되어서 윤회하고 묶이고 해방된다.',

'(보충설명) ',
'tasmāt na badhyate-asau na mucyate na api saṃsarati kaścit |saṃsarati badhyate mucyate ca nānāśrayā prakṛtiḥ ||',

'tasmāt: 그러므로',
'na: 아니다',
'badhyate:묶이다',
'asau: (먼것을 지시하는 adas의 남성여성 단수 주격) 그는',
'na:아니다',
'mucyate: 해방되다',
'na: 아니다',
'api:또한',
'saṃsarati: 윤회하다',
'kaścit: 누구도',
'saṃsarati: 윤회하다',
'badhyate: 묶이다',
'mucyate: 해방되다',
'ca: 또한',
'nānā: 다양한',
'āśri:(~ayā, 여성 단수 구격) 결합, 의존',
'prakṛti:쁘라끄리띠',
],
[
'sk63 원질의 해방, 정신을 위함:',
'그러나 정말이지 원질(쁘라끄리띠)은 자신을 자신에 의해서 7 가지* 형태(루우빠)로 묶는다/ 또한 그녀(쁘라끄리띠)는 정말이지 정신(뿌루샤)을 위한 한 가지 형태로 벗어나게 된다.',

'(보충설명) ',
'rūpaiḥ saptabhiḥ eva tu badhnāti ātmānam ātmanā prakṛtiḥ |saiva ca purṣārthaṃ prati vimocayati eka rūpeṇa ||',

'rūpa:(~iḥ, 복수 구격) 형태들로',
'sapta:(~bhiḥ, 복수 구격) 7 가지로, (*선, 악, 열정, 냉정, 힘, 무력, 무지) ',
'eva: 참으로',
'tu: 그러나',
'badhnāti: 묶다',
'ātmānam: 자신을',
'ātmanā: 자신으로',
'prakṛtiḥ:쁘라끄리띠',
'sā: 그녀(쁘라끄리띠)',
'eva: 정말이지',
'ca: 또한',
'purṣa: 뿌루샤',
'artha: 목적으로 ',
'prati: 향함, 관련',
'vimocayati:(vimuc +aya, 사역) 해방, 벗어남 ',
'eka: 하나(*지혜, 식별지)',
'rūpa:(~eṇa, 구격) 형태로',
],
[
'sk64 무아 독존 지혜:',
'나는 있지 않다, 나의 것은 아니다, 나는 아니다 라고 이렇게 원리를 반복 수행함으로써,(더 알아야할) 남은 것이 없고/ 전도된 것이 없어져 정화된 독존의 지혜가 일어난다.',

'(보충설명) ',
'evaṃ tattvābhyāsāt na asmi na me na aham iti apariśeṣam |aviparyayāt viśuddhaṃ kevalam utpadyate jñānam ||',

'evaṃ: 이렇게',
'tattva: 원리',
'abhyāsāt: 반복수행으로',
'na: 아니다',
'asmi: 있다',
'na: 아니다',
'me: 나의 (것)',
'na: 나',
'aham:나는',
'iti:라고',
'apariśeṣa: 남은 것이 없는',
'aviparyayāt: 전도됨이 없는',
'viśuddha: 정화, 악으로부터 벗어남',
'kevala: 독존, ',
'utpadyate: 일어난다, 생겨난다',
'jñāna: 지혜',
],
[
'sk65 원질 멈춤 정신 투명하게 드러남:',
'그(쁘라끄리띠) 움직임이 멈추고 대상(목적)의 힘으로 7 가지* (묶인) 형태(루우빠)가 사라지고/ 원질(쁘라끄리띠)을 보는 정신(뿌루샤)이 관객처럼 투명하게 자리잡는다. ',

'(보충설명) ',
'tena nivṛttapras(ś)ava(ā) arthavaśāt sapta rūpa vinivṛttām |prakṛtiṃ paśyati puruṣaḥ prekṣakavat avasthitaḥ svacchaḥ ||',

'tena: 그것으로',
'nivṛtta: 되돌아감, 멈춤',
'prasava: 움직임, 작동',
'artha: 대상, 목적',
'vaśa: (~āt,종격)의지, 힘',
'sapta:7(*앞 경문63 참조)',
'rūpa: 형태, 색',
'vinivṛttām: 사라짐',
'prakṛtiṃ ',
'paśyati: 보다',
'puruṣaḥ: 뿌루샤',
'prekṣakavat: 관객, 구경꾼 처럼',
'avasthita: 자리잡은, 다가온',
'svaccha: 투명한',
],
[
'sk66 정신에 보여지면, 창조 멈춤:',
'나에게 보여졌다 하고, 나는 평정하게 하나로 보여졌다 하고, 다른 것은 물러난다./ 결합이 있을지라도 창조의 동기는 없어진다. ',

'(보충설명) ',
'dṛṣṭā mayā iti upekṣakaḥ ekaḥ dṛṣṭā aham iti uparamati anya |sati saṃyoge-api prayojanaṃ nāsti sargasya ||',

'dṛṣṭā: 본',
'mayā: 나에 의해',
'iti: ~라고',
'upekṣakaḥ: 평정 ',
'ekaḥ: 하나',
'dṛṣṭā: 본',
'aham: 나',
'iti:~라고',
'uparamati:(원형 uparam) 물러난다. 멈춘다',
'anya: 다른',
'sati: 존재, 있다.',
'saṃyoge: 결합',
'api:도',
'prayojana: 동기, 경우 ',
'nāsti: 없다',
'sargasya: 창조의',
],
[
'sk67 완전한 지혜 남은 잠재력 도공 물레:',
'(뿌루샤는)완전한 지혜를 획득하여 선(다르마) 등의 원인 없는 상태에 도달한다/(하지만) 미세몸(샤리라)은 남아있는 잠재력(쌈쓰까라)의 힘으로 도공의 물레바퀴처럼 둘러싸여 돈다. ',

'(보충설명) ',
'samyak-jñāna adhigamāt dharmadīnām akāraṇa prāptau |tiṣṭhati saṃskāra vaśāt cakra bhramivat dhṛta śarīraḥ ||',

'samyak: 완전, 무상',
'jñāna: 지혜',
'adhigama:(~āt, 종격) 획득',
'dharma: 다르마',
'adīnām: 등의 ',
'akāraṇa: 원인이 없는 (상태)',
'prāpti:(~au, 단수 처격) 도달, 이름',
'tiṣṭhati: 남다',
'saṃskāra: 윤회',
'vaśa:(~āt, 종격) 힘, 지배',
'cakra: 수레바퀴',
'bhramivat: 도자기 공 처럼',
'dhṛta: 둘러싸인',
'śarīraḥ: 미세몸',
],
[
'sk68 불멸성 절대성 독존:',
'미세몸(샤리라)의 분리에 도달하는 목적을 완수하고 토대가 멈춤으로/ 절대성 불멸성의 두가지 독존을 획득한다.',

'(보충설명) ',
'prāpte śarīrabhede caritārthatvāt pradhāna vinivṛtteḥ |aikāṅtikam ātyaṅtikam ubhayaṃ kaivalyaṃ prāpnoti ||',

'prāpte: 획득하다. 얻다.',
'śarīra: 미세몸',
'bheda: 분리',
'caritārthatvāt: 목적을 완수하고나서',
'pradhāna: 토대',
'vinivṛtti:(~eḥ, 단수 종격속격) 멈춤, 사라짐',
'aikāṅtika: 절대성',
'ātyaṅtika: 불멸성',
'ubhaya: 둘',
'kaivalya: 독존',
'prāpnoti: 획득하다',
],
[
'sk69 정신 목적 지혜의 비밀:',
'뿌루샤 목적의 이 지혜의 비밀은 지고의 성자에 의해 모두 밝혀졌다/ 유지, 산출, 융합이 (일어난다고) 생각되는 그 요소(오대)들이 있는 곳에서.',

'(보충설명) ',
'puruṣārtha jñānam idaṃ guhyaṃ paramarṣiṇā samākhyātam |sthiti utpatti pralayaḥ cintyaṅte yatṛa bhūtānām ||',

'puruṣārtha: 뿌루샤 목적',
'jñānam: 지혜',
'idaṃ: 이것',
'guhyaṃ: 비밀',
'paramarṣiṇā: 지고의 성자에 의해',
'samākhyātam: 모두 밝혀진',
'sthiti: 유지',
'utpatti: 산출',
'pralayaḥ: 융합',
'cintyaṅte: 생각되다',
'yatṛa: 그곳',
'bhūta: (~ānām, 복수 속격) 요소(오대)로 된 자들의',
],
[
'sk70 까삘라 아수리 빤짜시카:',
'이 (고통의) 정화수단의 최고의 비밀은 무니(까삘라 선인)가 아수리에게 자비로 가르쳤고/ 아수리도 빤짜시카에게 (가르쳤고), 그(빤짜시키)에 의해 많은 종류가 체계적으로 행해졌다.',

'(보충설명) ',
'etat pavitram agryam muniḥ āsuraye-anukaṃpayā [pradadau]|āsuriḥ api pañcaśikhāya tena ca bahudhā kṛtaṃ tantram ||',

'etat: 이것',
'pavitram: 정화수단(세 가지 고통으로부터)',
'agryam: 최고의 것',
'muniḥ: 무니, 성자',
'āsuri: (~aye, 남성 단수 위격) 아수리에게',
'anukaṃpā:(~ayā, 여성 단수 구격) 자비로',
'pradadau: 가르쳐주었다',
'āsuriḥ: 아수리',
'api: ~도',
'pañcaśikha:(~āya, 남성 단수 위격) 빤짜시카에게 ',
'tena: 그에 의해서',
'ca: 또한',
'bahudhā: 많은 종류 ',
'kṛtaṃ: 행해짐',
'tantra: 체계, 핵심',
],
[
'sk71 끄리쉬나 바램 성취:',
'제자들이 끊어지지 않고 전해온 것을 이쉬와라 끄리쉬나가 또 이 아르야 싯귀들로/ 요약했다. 성자의 바램(헌신)으로 (내용을) 완전한 이해하고 나서, (이것은) 성취되었다.',

'(보충설명) ',
'śiṣya-paraṃparyā-agatam īśvarakṛṣṇena caitad āryābhiḥ |saṃkṣiptam āryamatinā saṃyak-vijñāya siddhāntam ||',

'śiṣya: 제자',
'pā[a]raṃparya: 끊어지지 않고, 대대로 전해진',
'āgata: 전해옴, 내려옴',
'īśvarakṛṣṇena: 이쉬와라 끄리쉬나에 의해',
'caitad: ca etad',
'āryā: (~bhiḥ, 여성 복수 구격) 아르야 싯귀들로',
'saṃkṣiptam: 요약',
'ārya: 성자, ',
'mati: (~nā, 남성 단수 구격) 바램, 헌신, 기도',
'saṃyak: 완전한',
'vijñāya: 지혜로',
'siddhāntam: 성취가 이루어짐',
],
[
'sk72 싸앙크야 까리까 체계:',
'70 개 내용들은 바로 (쁘라바짜냐) 60개(6권) 체계 전체의 내용들이다./ 설명들은 버리고 다른 말은 피했다.',

'(보충설명) ',
'saptatyāṃ kila ye arthāḥ te arthāḥ kṛtsnasya ṣaṣṭitantrasya |ākhyāyikā-virahitāḥ paravāda-vivarjitāḥ cā api ||',

'saptati:(~āṃ, 복수 속격) 70',
'kila: 진실로, 바로',
'ye:(남성 복수 주격)',
'artha:(~āḥ, 복수 주격) 의미, 대상, 내용',
'te: 그 ',
'artha:(~āḥ, 복수 주격) 의미, 대상, 내용',
'kṛtsna: (~sya, 속격) 전체',
'ṣaṣṭi:60 ( *60은 싸앙크야 쁘라바챠나 수뜨라 6권을 가리킴)',
'tantra: (~sya, 속격) 조직 ',
'ākhyāyikā: 짧은 대화(설명?), 실제 예',
'virahita:(~āḥ, 복수 주격) 버린, 벗어난',
'paravāda: 다른 말',
'vivarjita: (~āḥ, 복수 주격) 피한, 버린',
'cā: ',
'api:',
],
[
'sk73 원판의 거울:',
'그러므로 싸마사에서 본 이 가르침은 다른 내용이나 빠진 것이 없고./ 체계적이고 또 풍부한 형태의 원판이 함께 비추는 거울과 같다.',

'(보충설명) ',
'tasmāt samāsa-dṛṣṭaṃ śāstram idaṃ nārthataḥ ca parihīnam |tantrasya ca bṛhanmūrteḥ darpaṇa-saṅkrāntam-iva biṃbam ||',

'tasmāt: 그러므로',
'samāsa: 전체',
'dṛṣṭaṃ: 본',
'śāstram: 가르침',
'idaṃ: 이',
'na: 아니다. 없다',
'arthatas: (다른) 특정한 목적을 위해서, 정말이지',
'ca: 또한',
'parihīna: 빠진, 생략된',
'tantra: 체계',
'ca: 또한',
'bṛhan:bṛhat: 큰, 풍부한',
'mūrti: (~eḥ, 남성 단수 종격속격) 형체',
'darpaṇa: 거울',
'saṃ[ṅ]krānta: 함께 가는, 비춰진',
'iva: 처럼',
'bim(ṃ)ba: 원판, 영역, 거울',
]
];

//참고 문헌*
const samKarBooks= [
'Samkhya Karika of Isvara KRSNa with the Tattva Kaumudi of Sri Vacaspati Misra by Swami Virupashananda, 출판년표기 없음. (출판인 노트 Madras, Nov. 1995. )',

'The Sacred Books of Hindus. vol.11 SamKhya Philosophy ((1)Samkhya Pravacana Sutram, with the Vrtti of Aniruddha and the Bhasya of VijNana BhikSu and Extracts from the vrtti sAra of mahAdeva Vedantin (2)Tattva samAsa (3)sAmkhya kArikA (4)PancaSikhA SUtram ) translated by Nadalal Sinha, M.A., B.L.,P.C.S. 1915',

'Sankhya Philosophy by ?sh Chandra Banerji, Fasciculus 1, Sankhya Karika with Gaudapa’s Scholia and Narayqana’s Gloss, Calcutta 년도표기 없음(1900년 전후?)',

-'Aniruddha’s Comentary And the Original Part of Vedantin Mahadeva’s Comentary on the Samkhya Sutras(6권), Translated By Richard Garbe, Calcutta 1892',

'Samkhya Aphorisms of Kapila with Illustrative Extracts from the Commentaries, translated by James R. Ballantyne, LL. D. Third Edition. London 1885'
];


